stages:
  - apply
  - deploy

terraform_apply:
  stage: apply
  image: hashicorp/terraform:latest
  script:
    - init
    - plan -out=tfplan
    - apply -auto-approve tfplan
  only:
    - master

terraform_deploy:
  stage: deploy
  image: google/cloud-sdk:latest
  script: 
    - gcloud app deploy
  only:
    - master