image: hashicorp/terraform:latest

stages:
    - apply
    - deploy

before_script: 
    # Ensure the script is executable and run it to exchange the token for GCP credentials
    script:
        - chmod +x infra/exchange_token.sh
        - ./infra/exchange_token.sh


terraform_apply:
    stage: apply
    image: hashicorp/terraform:latest
    script:
        - terraform init
        - terraform plan -out=tfplan
        - terraform apply -auto-approve tfplan
    only:
        - master

terraform_deploy:
    stage: deploy
    image: google/cloud-sdk:latest
    script: 
        - gcloud app deploy
    only:
        - master
