stages:
  - test

test_before_script:
  stage: test
  before_script:
    - echo "Starting before_script"
    - set -x
    - chmod +x infra/exchange_token.sh
    - ./infra/exchange_token.sh
    - echo "Completed before_script"