stages:
  - test


test_script:
  stage: test
  # Ensure the script is executable and run it to exchange the token for GCP credentials
  script:
    - echo "Starting before_script"
    - set -x
    - chmod +x infra/exchange_token.sh
    - ./infra/exchange_token.sh
    - echo "Completed before_script"

