stages:
  - test

get-crendentials:
  image: dwdraju/alpine-curl-jq
  stage: test
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://gitlab.com
  script:
    - chmod +x infra/exchange_token.sh
    - ./infra/exchange_token.sh
  

 








