stages:
  - apply

image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

terraform_apply:
  stage: apply
  script:
    - echo "Installing dependencies"
    - apk update && apk add --no-cache curl jq
    - echo "dependencies installed" 
    - terraform init
    - terraform plan -out=tfplan
    - terraform apply -auto-approve tfplan
  only:
    - master




