stages:
  - test-auth
  - test-sh

get-crendentials:
  image: google/cloud-sdk:slim
  stage: test-auth
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://gitlab.com
  script:
    - echo ${GITLAB_OIDC_TOKEN} > .ci_job_jwt_file
    - gcloud iam workload-identity-pools create-cred-config ${GCP_WORKLOAD_IDENTITY_PROVIDER}
      --service-account="${GCP_SERVICE_ACCOUNT}"
      --output-file=.gcp_temp_cred.json
      --credential-source-file=.ci_job_jwt_file
      --aud=https://accounts.google.com
    - gcloud auth login --cred-file=`pwd`/.gcp_temp_cred.json
    - gcloud auth list

get-sh:
  image: dwdraju/alpine-curl-jq
  stage: test-sh
  script:
    - chmod +x infra/exchange_token.sh
    - ./infra/exchange_token.sh











