before_script:
  # Ensure the script is executable and run it to exchange the token for GCP credentials
  - echo "Starting before_script"
  - ls -l
  - set -x
  - chmod +x infra/exchange_token.sh
  - ./infra/exchange_token.sh
  - echo "Completed before_script"

stages:
  - apply



terraform_apply:
  stage: apply
  image:
    name: hashicorp/terraform:light
    entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script:
    - echo "Installing dependencies"
    - apk update && apk add --no-cache curl jq
    - echo "dependencies installed" 
    - terraform init
    - terraform plan -out=tfplan
    - terraform apply -auto-approve tfplan
  only:
    - master




