runtime: python311

instance_class: F1

service: default

entrypoint: gunicorn -b :$PORT app:app --log-level debug

automatic_scaling:
  min_instances: 1
  max_instances: 2

beta_settings:
  cloud_sql_instances: cornhole-score-app:us-central1:mysql-instance